---
format:
  revealjs:
    incremental: false
    css: ../styles.css
execute: 
  echo: true
---

# On-Demand: Phylogeny and Classification

## All organisms are related by descent from a common ancestor

- Earth began about 4.5 billion years ago

- Life on earth began about 3.6 billion years ago

- All life on earth is organized into cells and uses DNA
  - This indicates a **single origin** of life on earth
  - **All organisms** that live today **are related to each other**

## A phylogeny represents how organisms are related

- The name of the organism (usually, the species) is written on one side (***tips***)

- The lines connecting the names indicate evolution within that species

- ***Nodes*** (where lines come together) indicate a **common ancestor** shared between species

- In theory, we can draw the entire evolutionary history of earth using a phylogeny

## The most important part of a phylogeny is how the lines connect

- The order of tips does not matter (one living species on the phylogeny is not "more evolved" than another)

- This may be confusing if you are used to thinking of humans as being "highly evolved"

- Since there is one common origin of life on earth, that means all lineages living now are equally old
  - We just took different pathways to get here

## We must use indirect evidence to infer how evolution happened

- In most cases, humans cannot watch lineages splitting

- We have to use **indirect evidence**
  - Inherited characteristics, such as physical appearance or DNA
  - These are called ***traits***

## Traits that were inherited from a common ancestor are evidence for phylogeny

## Activity: Build Your Own Phylogeny (BYOP)

- In this activity, you will build a phylogeny of the following species:
  - Fish
  - Owl
  - Frog
  - Starfish
  - Cow

## Classification systems

- ***Taxonomy*** is the study of **naming organisms**

- A ***taxonomic classification*** is a way to **organize** names

- A classification is a **hierarchy** of nested groups
  - Each level of the hierarchy is called a ***taxonomic rank***
  - Each named group is called a ***taxon*** (plural: "taxa")

## Typical taxonomic classification

- Ranks: kingdom, phylum, order, class, family, genus, species, variety

- Taxa: 

## Classification should reflect evolution

- Groups of organisms that we recognize in the classification should share common evolutionary history

- Ideally